package com.psm.elearning.model;

import jakarta.validation.constraints.*;
import java.time.LocalDateTime;

/**
 * Certificate entity representing issued certificates.
 * Matches the Certificate table schema.
 * 
 * Uses Lombok for automatic getter/setter generation.
 * Uses Jakarta Bean Validation for input validation.
 */
public class Certificate {
    @NotNull(message = "Certificate ID cannot be null")
    private Integer certificateId;
    
    @NotNull(message = "Enrollment ID is required")
    private Integer enrollmentId;
    
    @NotBlank(message = "Certificate number is required")
    @Size(max = 100, message = "Certificate number must not exceed 100 characters")
    private String certificateNo;
    
    private LocalDateTime issueDate;
    
    @Size(max = 255, message = "QR code path must not exceed 255 characters")
    private String qrCodePath;
    
    @Size(max = 100, message = "Generated by field must not exceed 100 characters")
    private String generatedBy;
    
    @Size(max = 255, message = "Verification URL must not exceed 255 characters")
    private String verificationURL;

    @Size(max = 20, message = "Status must not exceed 20 characters")
    private String status;

    private LocalDateTime revokedAt;
    private Integer revokedBy;
    
    // Constructors
    public Certificate() {}
    
    public Certificate(Integer certificateId, Integer enrollmentId, String certificateNo,
                      LocalDateTime issueDate, String qrCodePath, String generatedBy,
                      String verificationURL, String status, LocalDateTime revokedAt, Integer revokedBy) {
        this.certificateId = certificateId;
        this.enrollmentId = enrollmentId;
        this.certificateNo = certificateNo;
        this.issueDate = issueDate;
        this.qrCodePath = qrCodePath;
        this.generatedBy = generatedBy;
        this.verificationURL = verificationURL;
        this.status = status;
        this.revokedAt = revokedAt;
        this.revokedBy = revokedBy;
    }
    
    // Getters and Setters
    public Integer getCertificateId() { return certificateId; }
    public void setCertificateId(Integer certificateId) { this.certificateId = certificateId; }
    
    public Integer getEnrollmentId() { return enrollmentId; }
    public void setEnrollmentId(Integer enrollmentId) { this.enrollmentId = enrollmentId; }
    
    public String getCertificateNo() { return certificateNo; }
    public void setCertificateNo(String certificateNo) { this.certificateNo = certificateNo; }
    
    public LocalDateTime getIssueDate() { return issueDate; }
    public void setIssueDate(LocalDateTime issueDate) { this.issueDate = issueDate; }
    
    public String getQrCodePath() { return qrCodePath; }
    public void setQrCodePath(String qrCodePath) { this.qrCodePath = qrCodePath; }
    
    public String getGeneratedBy() { return generatedBy; }
    public void setGeneratedBy(String generatedBy) { this.generatedBy = generatedBy; }
    
    public String getVerificationURL() { return verificationURL; }
    public void setVerificationURL(String verificationURL) { this.verificationURL = verificationURL; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getRevokedAt() { return revokedAt; }
    public void setRevokedAt(LocalDateTime revokedAt) { this.revokedAt = revokedAt; }

    public Integer getRevokedBy() { return revokedBy; }
    public void setRevokedBy(Integer revokedBy) { this.revokedBy = revokedBy; }
}






