<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certificate</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/landing.css">
    <style>
        body { background: #f3f4f6; margin: 0; font-family: 'Georgia', serif; }
        .wrap { max-width: 1100px; margin: 24px auto; padding: 0 12px; }
        .toolbar { display:flex; gap:10px; margin-bottom: 14px; }
        .btn { display:inline-block; padding:10px 14px; text-decoration:none; border:1px solid #1f2937; color:#111827; background:#fff; }
        .btn.primary { background:#1f2937; color:#fff; }
        .msg { background:#fff3cd; border:1px solid #f59e0b; padding:14px; color:#78350f; }

        .certificate {
            background: #fff;
            border: 14px solid #0f2a56;
            padding: 30px;
            position: relative;
            box-shadow: 0 14px 40px rgba(0,0,0,.08);
        }
        .certificate:before {
            content: "";
            position:absolute;
            inset: 10px;
            border: 2px solid #c9a227;
            pointer-events:none;
        }
        .title { text-align:center; font-size: 44px; font-weight:700; color:#0f2a56; margin-top: 10px; letter-spacing: 1px; }
        .subtitle { text-align:center; color:#374151; margin-top: 6px; font-size: 15px; text-transform: uppercase; letter-spacing: 2px; }
        .line { text-align:center; margin-top: 28px; font-size: 20px; color:#374151; }
        .name { text-align:center; margin-top: 14px; font-size: 42px; color:#111827; font-weight:700; border-bottom: 2px solid #c9a227; display:inline-block; padding: 0 18px 8px; }
        .center { text-align:center; }
        .details { margin-top: 22px; text-align:center; color:#1f2937; font-size: 18px; line-height:1.6; }
        .meta { margin-top: 30px; display:grid; grid-template-columns: repeat(3,1fr); gap: 18px; }
        .meta-box { border-top:2px solid #c9a227; padding-top:8px; font-size: 14px; color:#374151; }
        .meta-value { font-size: 15px; color:#111827; font-weight: 700; margin-top:4px; word-break: break-all; }
        .verify { margin-top: 20px; text-align:center; font-size: 12px; color:#4b5563; }

        @media print {
            .toolbar { display:none; }
            .wrap { margin:0; max-width:none; }
            body { background:#fff; }
            .certificate { box-shadow:none; }
        }
    </style>
</head>
<body>
<div class="wrap">
    <div class="toolbar">
        <a class="btn" href="${pageContext.request.contextPath}/student/enrollment-details?id=${enrollment.enrollmentId}">Back</a>
        <button class="btn primary" onclick="window.print()">Download / Print</button>
        <c:if test="${not empty certificate}">
            <a class="btn" target="_blank" href="${certificate.verificationURL}">Verify</a>
        </c:if>
    </div>

    <c:choose>
        <c:when test="${not eligible}">
            <div class="msg">
                Certificate is not available yet. Required: payment must be paid and course completion status must be Completed.
            </div>
        </c:when>
        <c:when test="${empty certificate}">
            <div class="msg">Certificate generation failed. Please refresh and try again.</div>
        </c:when>
        <c:otherwise>
            <section class="certificate">
                <div class="subtitle">PSM E-Learning Platform</div>
                <div class="title">Certificate of Completion</div>

                <div class="line">This is to certify that</div>
                <div class="center"><div class="name">${studentUser.fullName}</div></div>

                <div class="details">
                    Registration Number: <strong><c:out value="${studentProfile.regNumber}" default="N/A"/></strong><br>
                    has successfully completed the course<br>
                    <strong>${course.courseName}</strong>
                </div>

                <div class="meta">
                    <div class="meta-box">
                        Certificate Number
                        <div class="meta-value">${certificate.certificateNo}</div>
                    </div>
                    <div class="meta-box">
                        Issue Date
                        <div class="meta-value">${certificate.issueDate}</div>
                    </div>
                    <div class="meta-box">
                        Generated By
                        <div class="meta-value">${certificate.generatedBy}</div>
                    </div>
                </div>

                <div class="verify">
                    Verification URL: ${certificate.verificationURL}
                </div>
            </section>
        </c:otherwise>
    </c:choose>
</div>
</body>
</html>
