<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certificate Verification</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/landing.css">
    <style>
        body { font-family: Arial, sans-serif; background:#f8fafc; margin:0; }
        .wrap { max-width:900px; margin:30px auto; padding:0 12px; }
        .card { background:#fff; border:1px solid #e5e7eb; padding:20px; }
        .ok { color:#166534; border-left:4px solid #22c55e; background:#f0fdf4; padding:12px; margin-bottom:14px; }
        .bad { color:#991b1b; border-left:4px solid #ef4444; background:#fef2f2; padding:12px; margin-bottom:14px; }
        .grid { display:grid; grid-template-columns: 220px 1fr; gap:10px; }
        .lbl { color:#6b7280; }
        .val { font-weight:600; color:#111827; }
    </style>
</head>
<body>
<div class="wrap">
    <div class="card">
        <h2>Certificate Verification</h2>
        <c:choose>
            <c:when test="${valid}">
                <div class="ok">Valid certificate. This certificate was issued by PSM E-Learning.</div>
                <div class="grid">
                    <div class="lbl">Certificate Number</div><div class="val">${certificate.certificateNo}</div>
                    <div class="lbl">Student Name</div><div class="val"><c:out value="${studentUser.fullName}" default="-"/></div>
                    <div class="lbl">Registration Number</div><div class="val"><c:out value="${studentProfile.regNumber}" default="-"/></div>
                    <div class="lbl">Course</div><div class="val"><c:out value="${course.courseName}" default="-"/></div>
                    <div class="lbl">Issue Date</div>
                    <div class="val">
                        <c:choose>
                            <c:when test="${not empty certificate.issueDate}">
                                ${certificate.issueDate.toLocalDate()}
                            </c:when>
                            <c:otherwise>-</c:otherwise>
                        </c:choose>
                    </div>
                    <div class="lbl">Generated By</div><div class="val">${certificate.generatedBy}</div>
                </div>
            </c:when>
            <c:otherwise>
                <div class="bad">Invalid certificate. ${message}</div>
            </c:otherwise>
        </c:choose>
    </div>
</div>
</body>
</html>
