<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certificate Verification | PSM E-Learning</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/certificate-verify-v2.css">
</head>
<body class="cv-page">
<main class="cv-wrap">
    <section class="cv-card cv-hero">
        <div>
            <p class="cv-kicker">PSM E-Learning</p>
            <h1>Certificate Verification</h1>
            <p class="cv-sub">Validate certificate authenticity using an issued certificate code.</p>
        </div>
        <div class="cv-badge"><i class="fas fa-shield-check"></i> Trusted Verification</div>
    </section>

    <section class="cv-card">
        <form method="get" action="${pageContext.request.contextPath}/certificate/verify" class="cv-form">
            <label for="code">Certificate Code</label>
            <div class="cv-form-row">
                <input id="code" type="text" name="code" value="${checkedCode}" placeholder="e.g. PSM-CERT-20260223-ABC123" required>
                <button type="submit"><i class="fas fa-magnifying-glass"></i><span>Verify</span></button>
            </div>
        </form>
    </section>

    <section class="cv-card">
        <c:choose>
            <c:when test="${valid}">
                <div class="cv-status cv-ok">
                    <i class="fas fa-circle-check"></i>
                    <div>
                        <h3>Valid Certificate</h3>
                        <p>This certificate is authentic and issued by PSM E-Learning.</p>
                    </div>
                </div>
                <div class="cv-grid">
                    <div class="cv-label">Certificate Number</div><div class="cv-value">${certificate.certificateNo}</div>
                    <div class="cv-label">Student Name</div><div class="cv-value"><c:out value="${studentUser.fullName}" default="-"/></div>
                    <div class="cv-label">Registration Number</div><div class="cv-value"><c:out value="${studentProfile.regNumber}" default="-"/></div>
                    <div class="cv-label">Course</div><div class="cv-value"><c:out value="${course.courseName}" default="-"/></div>
                    <div class="cv-label">Issue Date</div>
                    <div class="cv-value">
                        <c:choose>
                            <c:when test="${not empty certificate.issueDate}">
                                ${certificate.issueDate.toLocalDate()}
                            </c:when>
                            <c:otherwise>-</c:otherwise>
                        </c:choose>
                    </div>
                    <div class="cv-label">Generated By</div><div class="cv-value"><c:out value="${certificate.generatedBy}" default="-"/></div>
                </div>
            </c:when>
            <c:otherwise>
                <div class="cv-status cv-bad">
                    <i class="fas fa-triangle-exclamation"></i>
                    <div>
                        <h3>Verification Failed</h3>
                        <p><c:out value="${message}" default="Certificate was not found."/></p>
                    </div>
                </div>
            </c:otherwise>
        </c:choose>
    </section>

    <section class="cv-footnote">
        <i class="fas fa-lock"></i>
        <span>Verification results are generated from official issuance records.</span>
    </section>
</main>
</body>
</html>
