<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register - PSM E-Learning</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/auth-v2.css">
</head>
<body class="av2-page">
    <main class="av2-shell av2-shell-register">
        <section class="av2-panel av2-brand" aria-hidden="true">
            <p class="av2-kicker">Student Onboarding</p>
            <h1>Create Account</h1>
            <div class="av2-scene" role="presentation">
                <span class="av2-obj av2-book" data-depth="16"></span>
                <span class="av2-obj av2-pen" data-depth="24"></span>
                <span class="av2-obj av2-cap" data-depth="12"></span>
                <span class="av2-obj av2-paper" data-depth="20"></span>
                <span class="av2-obj av2-ring" data-depth="28"></span>
            </div>
            <a class="av2-link" href="${pageContext.request.contextPath}/">Back to Home</a>
        </section>

        <section class="av2-panel av2-form-panel">
            <div class="av2-form-wrap">
                <header class="av2-form-head">
                    <h2>Register</h2>
                    <p>Fields marked with * are compulsory.</p>
                </header>

                <c:if test="${not empty error}">
                    <div class="av2-alert av2-alert-error">${error}</div>
                </c:if>

                <form action="${pageContext.request.contextPath}/register" method="post" class="av2-form av2-form-grid" novalidate>
                    <div class="av2-group">
                        <label for="fullName">Full Name *</label>
                        <input id="fullName" name="fullName" type="text" value="${param.fullName}" required>
                    </div>

                    <div class="av2-group">
                        <label for="email">Email *</label>
                        <input id="email" name="email" type="email" value="${param.email}" required>
                    </div>

                    <div class="av2-group">
                        <label for="phone">Phone Number *</label>
                        <input id="phone" name="phone" type="tel" value="${param.phone}" placeholder="e.g. +255712345678" required>
                    </div>

                    <div class="av2-group">
                        <label for="country">Country *</label>
                        <input id="country" name="country" type="text" value="${param.country}" required>
                    </div>

                    <div class="av2-group">
                        <label for="password">Password *</label>
                        <input id="password" name="password" type="password" required>
                        <small>Minimum 8 characters with uppercase, lowercase, number, and special character.</small>
                    </div>

                    <div class="av2-group">
                        <label for="confirmPassword">Confirm Password *</label>
                        <input id="confirmPassword" name="confirmPassword" type="password" required>
                    </div>

                    <div class="av2-meta">
                        Registration Number will be generated by the system after successful registration.
                    </div>

                    <button type="submit" class="av2-btn av2-btn-solid">Create Account</button>
                </form>

                <div class="av2-switch">
                    <span>Already have an account?</span>
                    <a href="${pageContext.request.contextPath}/login">Login</a>
                </div>
            </div>
        </section>
    </main>

    <script>
        (function () {
            var form = document.querySelector('.av2-form');
            if (!form) return;
            form.addEventListener('submit', function (e) {
                var password = document.getElementById('password').value;
                var confirmPassword = document.getElementById('confirmPassword').value;
                if (password !== confirmPassword) {
                    e.preventDefault();
                    alert('Passwords do not match.');
                }
            });
        })();
    </script>
    <script src="${pageContext.request.contextPath}/js/auth-v2.js"></script></body>
</html>


